apiVersion: v1
kind: Service
metadata:
  name: burpsuite
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: burpsuite
    app.kubernetes.io/instance: burpsuite
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
