name: Release
on:
  push:
    tags:
      - "*"

jobs:
  setup:
    if: github.event.base_ref == "refs/heads/master"
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get_tag.outputs.tag }}
    steps:
      - name: Get tag
        id: get_tag
        run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}

  container:
    name: Build and upload container
    needs:
      - setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}
          dockerfile: Dockerfile
          image: burpsuite
          tags: latest, ${{ needs.setup.outputs.tag }}
